import shutil
import tempfile
from pathlib import Path

import yaml
from sdlc_specs.snapshot import (
    Snapshot,
    apply_snapshot,
    apply_snapshot_text,
    content_sha256,
    intent_sha256,
    normalise,
    parse_snapshot_file,
    render_snapshot_file,
)
from sdlc_specs.spec import parse_spec, parse_spec_text

from tests.base import OfflineTestCase

FIXTURES = Path(__file__).resolve().parent / "fixtures"
GOLDEN = FIXTURES / "snapshot"
TITLE = "Prorate plan changes mid-cycle"


class NormaliseTest(OfflineTestCase):
    def test_line_endings_trailing_whitespace_and_blank_edges_do_not_change_the_hash(self):
        base = content_sha256(TITLE, "Line one\nLine two")
        for description in (
            "Line one  \r\nLine two\r\n",
            "\n\nLine one\nLine two\n\n\n",
            "Line one\t\rLine two",
            "   \nLine one\nLine two   \n \n",
        ):
            with self.subTest(description=description):
                self.assertEqual(content_sha256(TITLE, description), base)
        self.assertEqual(content_sha256(TITLE + "  \r\n", "Line one\nLine two"), base)

    def test_a_one_character_change_changes_the_hash(self):
        self.assertNotEqual(
            content_sha256(TITLE, "Line one\nLine twO"), content_sha256(TITLE, "Line one\nLine two")
        )
        self.assertNotEqual(content_sha256(TITLE + ".", "x"), content_sha256(TITLE, "x"))

    def test_inner_whitespace_and_inner_blank_lines_are_content(self):
        self.assertNotEqual(normalise("a  b"), normalise("a b"))
        self.assertNotEqual(normalise("a\n\n\nb"), normalise("a\nb"))
        self.assertEqual(normalise("  indented\n"), "  indented")

    def test_unicode_is_not_folded(self):
        self.assertNotEqual(normalise("é"), normalise("é"))

    def test_pinned_hash(self):
        # Computed independently with sha256sum over the normalised text. This value is committed
        # in product repos: never update it to make this test pass. A deliberate change needs a
        # new versioned algorithm, not an edit here.
        description = (
            "\r\n\r\nCustomers who change plan mid-cycle should pay or be credited the difference.  \r\n"
            "\r\n"
            "Applies to monthly plans. Uses the billing anchor, crédit included.\t\r\n\r\n"
        )
        self.assertEqual(
            content_sha256(TITLE + " ", description),
            "0b5993d2b60afbe2ca6f35377270ad23ae922c552b95d4e28328a8785250eba1",
        )

    def test_empty_description(self):
        self.assertEqual(content_sha256(TITLE, ""), content_sha256(TITLE, "\n  \n"))


class SnapshotFileTest(OfflineTestCase):
    def test_round_trip(self):
        description = "\r\nFirst paragraph.  \r\n\r\n- a list\r\n"
        text = render_snapshot_file("billing/api#123", TITLE, description, "2026-09-23T11:02:00Z")
        parsed = parse_snapshot_file(text)
        self.assertEqual(parsed.ref, "billing/api#123")
        self.assertEqual(parsed.sha256, content_sha256(TITLE, description))
        self.assertEqual(parsed.taken_at, "2026-09-23T11:02:00Z")
        self.assertEqual(parsed.title, TITLE)
        self.assertEqual(parsed.description, "First paragraph.\n\n- a list")
        self.assertEqual(content_sha256(parsed.title, parsed.description), parsed.sha256)

    def test_rendered_format(self):
        text = render_snapshot_file("ENG-7", "Title", "Body", "2026-09-23T11:02:00Z")
        sha = content_sha256("Title", "Body")
        self.assertEqual(
            text,
            "<!-- generated by tools/specs; do not edit -->\n"
            f"<!-- ticket: ENG-7  sha256: {sha}  taken: 2026-09-23T11:02:00Z -->\n"
            "# Title\n\nBody\n",
        )

    def test_empty_description_round_trips(self):
        parsed = parse_snapshot_file(render_snapshot_file("#1", "Title", "", "2026-09-23T11:02:00Z"))
        self.assertEqual(parsed.description, "")
        self.assertEqual(parsed.sha256, content_sha256("Title", ""))

    def test_hand_edit_is_detectable(self):
        text = render_snapshot_file("#1", "Title", "Body", "2026-09-23T11:02:00Z").replace("Body", "B0dy")
        parsed = parse_snapshot_file(text)
        self.assertNotEqual(content_sha256(parsed.title, parsed.description), parsed.sha256)

    def test_malformed_files(self):
        for text in ("", "# Title\n", "<!-- generated by tools/specs; do not edit -->\n<!-- nope -->\n# T\n"):
            with self.subTest(text=text):
                with self.assertRaises(ValueError):
                    parse_snapshot_file(text)

    def test_bad_inputs(self):
        with self.assertRaises(ValueError):
            render_snapshot_file("#1", "Two\nlines", "Body", "2026-09-23T11:02:00Z")
        with self.assertRaises(ValueError):
            render_snapshot_file("#1", "Title", "Body", "yesterday")


class ApplySnapshotTest(OfflineTestCase):
    def test_existing_block_is_replaced_and_nothing_else_changes(self):
        before = (GOLDEN / "before-existing.md").read_text()
        snapshot = Snapshot(
            content_sha256="1234567890123456789012345678901234567890123456789012345678901234",
            taken_at="2026-09-23T11:02:00Z",
            updated_at="2026-09-23T10:14:00Z",
        )
        after = apply_snapshot_text(before, snapshot, taken_by="jdoe")
        self.assertEqual(after.encode(), (GOLDEN / "after-existing.md").read_bytes())

    def test_all_digit_hash_stays_a_string(self):
        after = (GOLDEN / "after-existing.md").read_text()
        spec = parse_spec_text(after)
        self.assertEqual(
            spec.frontmatter["ticket"]["snapshot"]["content_sha256"],
            "1234567890123456789012345678901234567890123456789012345678901234",
        )

    def test_missing_block_is_inserted_under_ticket(self):
        before = (GOLDEN / "before-missing.md").read_text()
        snapshot = Snapshot(content_sha256="abcdef" * 10 + "abcd", taken_at="2026-09-23T11:02:00Z")
        after = apply_snapshot_text(before, snapshot, taken_by="yes")
        self.assertEqual(after.encode(), (GOLDEN / "after-missing.md").read_bytes())
        self.assertEqual(parse_spec_text(after).frontmatter["ticket"]["snapshot"]["taken_by"], "yes")

    def test_lines_outside_the_block_are_byte_identical(self):
        before = (GOLDEN / "before-existing.md").read_text().splitlines()
        after = (GOLDEN / "after-existing.md").read_text().splitlines()
        # The snapshot block spans lines 9-13 (1-based) in both; nothing outside it changes.
        self.assertEqual(before[:9], after[:9])
        self.assertEqual(before[13:], after[13:])
        self.assertNotEqual(before[9:13], after[9:13])

    def test_crlf_files_keep_crlf(self):
        before = (GOLDEN / "before-missing.md").read_text().replace("\n", "\r\n")
        snapshot = Snapshot(content_sha256="ab" * 32, taken_at="2026-09-23T11:02:00Z")
        after = apply_snapshot_text(before, snapshot, taken_by="jdoe")
        self.assertNotIn("\n", after.replace("\r\n", ""))

    def test_applying_twice_is_stable(self):
        before = (GOLDEN / "before-missing.md").read_text()
        snapshot = Snapshot(content_sha256="ab" * 32, taken_at="2026-09-23T11:02:00Z")
        once = apply_snapshot_text(before, snapshot, taken_by="jdoe")
        self.assertEqual(apply_snapshot_text(once, snapshot, taken_by="jdoe"), once)

    def test_flow_style_ticket_is_refused(self):
        text = "---\nid: x\nticket: {system: github, ref: '#1'}\n---\n"
        with self.assertRaises(ValueError):
            apply_snapshot_text(text, Snapshot("ab" * 32, "2026-09-23T11:02:00Z"), taken_by="jdoe")

    def test_file_wrapper_writes_in_place(self):
        tmp = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, tmp)
        path = tmp / "spec.md"
        shutil.copy(GOLDEN / "before-missing.md", path)
        apply_snapshot(path, Snapshot("abcdef" * 10 + "abcd", "2026-09-23T11:02:00Z"), taken_by="yes")
        self.assertEqual(path.read_bytes(), (GOLDEN / "after-missing.md").read_bytes())


class WorkflowExampleFixtureTest(OfflineTestCase):
    """The workflow's example spec carries a real snapshot, so it can serve as a lint fixture."""

    def test_snapshot_file_matches_the_frontmatter(self):
        spec_dir = FIXTURES / "specs" / "123-prorate-plan-changes"
        spec = parse_spec(spec_dir / "spec.md")
        parsed = parse_snapshot_file((spec_dir / "ticket.snapshot.md").read_text())
        self.assertEqual(content_sha256(parsed.title, parsed.description), parsed.sha256)
        self.assertEqual(spec.frontmatter["ticket"]["snapshot"]["content_sha256"], parsed.sha256)
        self.assertEqual(parsed.ref, spec.frontmatter["ticket"]["ref"])
        # The rest of the example, comments included, is unchanged from the workflow document.
        raw = (spec_dir / "spec.md").read_text()
        self.assertIn("updated_at: 2026-09-23T10:14:00Z # informational only, see 5.1", raw)
        self.assertIsInstance(yaml.safe_load(raw.split("---")[1]), dict)


class IntentHashTest(OfflineTestCase):
    def test_pinned_intent_hash(self):
        # Computed independently: printf '# Intent: x\\n\\nLine' | sha256sum. This value is
        # committed in product repos: never update it to make this test pass.
        self.assertEqual(
            intent_sha256("\r\n# Intent: x  \r\n\r\nLine\t\r\n\r\n"),
            "28ceecc90a8e69fc7e826cb28db2f46df53c4415d0aeb1284a710c97be6fe24d",
        )

    def test_whole_file_is_hashed(self):
        self.assertNotEqual(intent_sha256("# Intent: x\n\nA"), intent_sha256("# Intent: x\n\nB"))
