"""The ticket snapshot: normalisation, content hash, `ticket.snapshot.md`, and the frontmatter block.

The hash is the staleness anchor. It is committed in product repos and compared against the live
ticket by the pipeline, so the algorithm below is frozen: changing it would make every committed
snapshot look stale. If it must ever change, the new one gets a versioned prefix
(`sha256v2:...`) and both are accepted during migration. Never edit it silently.
"""

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

from .frontmatter import block_end, field_comments, indent_of, scalar, split_lines
from .spec import parse_spec_text

GENERATED_MARKER = "<!-- generated by tools/specs; do not edit -->"
_HEADER = re.compile(r"^<!-- ticket: (?P<ref>.+?)  sha256: (?P<sha>[0-9a-f]{64})  taken: (?P<taken>\S+) -->$")
_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")


def normalise(text: str) -> str:
    """Frozen: CRLF and lone CR become LF, trailing whitespace is stripped from every line, and
    leading and trailing blank lines are dropped. Nothing else: no Unicode normalisation, no
    changes inside a line. "Whitespace" is Python's `str.rstrip()` definition, which includes
    tabs, form feeds and Unicode spaces; that definition is part of the frozen algorithm.
    """
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def content_sha256(title: str, description: str) -> str:
    """Frozen: lowercase hex sha256 of `normalise(title) + "\\n\\n" + normalise(description)`, UTF-8."""
    payload = normalise(title) + "\n\n" + normalise(description)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def intent_sha256(text: str) -> str:
    """Frozen: lowercase hex sha256 of `normalise(text)`, UTF-8, over a whole intent file.

    Recorded in a spec's frontmatter when the spec is written, and compared later to tell the
    engineer the intent has changed since. Committed in product repos, so the same rule as
    `content_sha256` applies: never change it silently; a new algorithm needs a new name.
    """
    return hashlib.sha256(normalise(text).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class Snapshot:
    content_sha256: str
    taken_at: str  # UTC, YYYY-MM-DDTHH:MM:SSZ
    updated_at: str | None = None  # the ticket's own updated_at, informational only


@dataclass(frozen=True)
class SnapshotFile:
    ref: str
    sha256: str
    taken_at: str
    title: str
    description: str  # normalised


def _check_timestamp(value: str, name: str) -> None:
    if not _TIMESTAMP.match(value):
        raise ValueError(f"{name} must be UTC YYYY-MM-DDTHH:MM:SSZ, got {value!r}")


def render_snapshot_file(ticket_ref: str, title: str, description: str, taken_at: str) -> str:
    """The `ticket.snapshot.md` receipt: the exact intent a spec was written against."""
    _check_timestamp(taken_at, "taken_at")
    clean_title = normalise(title)
    if "\n" in clean_title:
        raise ValueError("a ticket title must be a single line")
    clean_description = normalise(description)
    sha = content_sha256(title, description)
    out = [
        GENERATED_MARKER,
        f"<!-- ticket: {ticket_ref}  sha256: {sha}  taken: {taken_at} -->",
        f"# {clean_title}",
    ]
    if clean_description:
        out += ["", clean_description]
    return "\n".join(out) + "\n"


def parse_snapshot_file(text: str) -> SnapshotFile:
    """Read a snapshot file back. The body is returned so callers can recompute the hash and
    catch a hand edit, which the header alone would hide."""
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    if len(lines) < 3 or lines[0] != GENERATED_MARKER:
        raise ValueError("not a generated ticket snapshot (first line is not the generated marker)")
    header = _HEADER.match(lines[1])
    if not header:
        raise ValueError("line 2 is not a snapshot header (ticket, sha256, taken)")
    if not lines[2].startswith("# "):
        raise ValueError("line 3 is not the ticket title heading")
    if len(lines) > 3 and lines[3].strip():
        raise ValueError("line 4 must be blank")
    return SnapshotFile(
        ref=header["ref"],
        sha256=header["sha"],
        taken_at=header["taken"],
        title=lines[2][2:],
        description=normalise("\n".join(lines[4:])),
    )


def apply_snapshot(spec_path: Path, snapshot: Snapshot, taken_by: str) -> None:
    text = spec_path.read_bytes().decode("utf-8")
    spec_path.write_bytes(apply_snapshot_text(text, snapshot, taken_by).encode("utf-8"))


def apply_snapshot_text(text: str, snapshot: Snapshot, taken_by: str) -> str:
    """Rewrite only the `ticket.snapshot` block of the frontmatter, inserting it under `ticket:`
    when absent. Every other byte of the file is kept: a YAML round trip would reorder keys and
    drop comments. A trailing comment on a field survives; comment lines inside the block, which
    the tool owns, do not.
    """
    _check_timestamp(snapshot.taken_at, "taken_at")
    if snapshot.updated_at is not None:
        _check_timestamp(snapshot.updated_at, "updated_at")
    lines, newline = split_lines(text)
    spec = parse_spec_text("\n".join(lines))
    fm_end = spec.frontmatter_end_line - 1  # index of the closing ---

    if "ticket" not in spec.key_lines:
        raise ValueError("the frontmatter has no ticket mapping")
    ticket = spec.key_lines["ticket"] - 1
    ticket_indent = indent_of(lines[ticket])
    children = [
        spec.key_lines[k] - 1 for k in spec.key_lines if k.startswith("ticket.") and k.count(".") == 1
    ]
    if not children or min(children) == ticket:
        raise ValueError("ticket must be a block mapping (one key per line) to be edited in place")
    child_indent = indent_of(lines[min(children)])
    step = child_indent - ticket_indent

    values = [("content_sha256", scalar(snapshot.content_sha256))]
    if snapshot.updated_at is not None:
        values.append(("updated_at", snapshot.updated_at))
    values += [("taken_by", scalar(taken_by)), ("taken_at", snapshot.taken_at)]

    if "ticket.snapshot" in spec.key_lines:
        start = spec.key_lines["ticket.snapshot"] - 1
        end = block_end(lines, start, fm_end)
        old_block = lines[start + 1 : end + 1]
        comments = field_comments(old_block)
        field_lines = [ln for ln in old_block if ln.strip() and not ln.strip().startswith("#")]
        field_indent = indent_of(field_lines[0]) if field_lines else indent_of(lines[start]) + step
        head = lines[start] if lines[start].rstrip().split("#")[0].rstrip().endswith(":") else None
        head = head or " " * indent_of(lines[start]) + "snapshot:"
        new = [head] + [f"{' ' * field_indent}{k}: {v}{comments.get(k, '')}" for k, v in values]
        lines[start : end + 1] = new
    else:
        end = block_end(lines, ticket, fm_end)
        new = [" " * child_indent + "snapshot:"] + [
            f"{' ' * (child_indent + step)}{k}: {v}" for k, v in values
        ]
        lines[end + 1 : end + 1] = new
    return newline.join(lines)
